name: Docker Compose CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  compose-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker (optional)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}   
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and start services
        run: |
          docker compose up --build -d
          # wait for services (simple wait, or check health)
          sleep 5

      - name: Run tests inside web container
        run: docker compose exec -T web pytest -q

      - name: Hit health and root endpoints from runner
        run: |
          # Try curl to web via localhost (since ports mapped)
          # fallback: use docker compose exec if ports not mapped
          curl --fail http://localhost:5000/health
          curl --fail http://localhost:5000/

      - name: Tear down
        if: always()
        run: docker compose down --volumes --remove-orphans
