name : BASIC-CI 

on: 
  push :
    branches: [ main ]


jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository 
      - uses: actions/chechout@v4         

      - name: Confirm push
      - uses: echo "Code Push Successfully"
      